### ISSUE TITLE
本地保存路径怎么写

### ISSUE THREAD

**Issue by giuem** [abelyao/qiniu-backup#1]
`D:\Desktop\qiniu-backup-master\backup`和`D:\Desktop\qiniu-backup-master\backup\`都报错

**Comment by abelyao** [comment]
最新版本的程序中增加了报错信息输出，你看看是什么异常，不一定是路径问题。

**Comment by giuem** [comment]
@abelyao 文件夹是要先创建好吗？

**Comment by abelyao** [comment]
一般来说是不需要的，代码中有判断和自动创建的功能，除非权限限制了不能创建目录。
